#!/bin/bash

diff="diff -iad"

declare -a file_base=("address2" "address" "d-all" "d-inverted" "d" "p-all" "range2" "range3" "range4" "range5" "range6" "range7" "range" "y")

# Loop to test all files in array
for file in "${file_base[@]}"; do

    file_sed="tests/$file.sed"
    file_c="tests/$file.c"               # c file generated by sed2c
    file_in="tests/$file.in"             # The in file
    file_out_val="tests/$file.out"       # The out file to check against
    file_out_tst="tests/$file.out.tst"   # The outfile from test application

    # Validate infile exists (do the same for out validate file)
    if [ ! -f "$file_in" ]; then
        printf "In file %s is missing\n" "$file_in"
        continue;
    fi
    if [ ! -f "$file_out_val" ]; then
        printf "Validation file %s is missing\n" "$file_out_val"
        continue;
    fi

    printf "Testing against %s\n" "$file_in"

    # Test
    $(eval "./app $file_sed $file_c")
    $(eval "gcc $file_c")
    $(eval "./a.out $file_in" > "$file_out_tst")

    # Execute diff
    $diff "$file_out_tst" "$file_out_val"

    e_code=$?
    if [ $e_code != 0 ]; then
            printf "TEST FAIL : %d\n" "$e_code"
            $(eval "rm $file_c $file_out_tst")
    else
            printf "TEST OK!\n"
            $(eval "rm $file_c $file_out_tst")
    fi

    # Pause by prompt
    read -p "Enter a to abort, anything else to continue: " input_data
    # Iff input is "a" then abort
    [ "$input_data" == "a" ] && break

done

exit 0
